CREATE DATABASE IF NOT EXISTS CENTRANZ;

USE  CENTRANZ;


CREATE TABLE IF NOT EXISTS `AGE_BAND` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `CODE` VARCHAR(64) NULL,
    `DESCRIPTION` VARCHAR(128) NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `RACE` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `CODE` VARCHAR(64) NULL,
    `DESCRIPTION` VARCHAR(128) NULL,
    PRIMARY KEY (`ID`)
);
  
CREATE TABLE IF NOT EXISTS `YEAR` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `CODE` VARCHAR(64) NULL,
    `DESCRIPTION` VARCHAR(128) NULL,
    PRIMARY KEY (`ID`)
);
  
CREATE TABLE IF NOT EXISTS `MARITAL_STATUS` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `CODE` VARCHAR(64) NULL,
    `DESCRIPTION` VARCHAR(128) NULL,
    PRIMARY KEY (`ID`)
);
  
CREATE TABLE IF NOT EXISTS `RESIDENCE` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `CODE` VARCHAR(64) NULL,
    `DESCRIPTION` VARCHAR(128) NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `DISABILITY_STATUS` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `CODE` VARCHAR(64) NULL,
    `DESCRIPTION` VARCHAR(128) NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `FAMILY_STATUS` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `CODE` VARCHAR(64) NULL,
    `DESCRIPTION` VARCHAR(128) NULL,
    PRIMARY KEY (`ID`)
);
  
CREATE TABLE IF NOT EXISTS `NATIVITY` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `CODE` VARCHAR(64) NULL,
    `DESCRIPTION` VARCHAR(128) NULL,
    PRIMARY KEY (`ID`)
);
  
CREATE TABLE IF NOT EXISTS `REGION` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `CODE` VARCHAR(64) NULL,
    `DESCRIPTION` VARCHAR(128) NULL,
    PRIMARY KEY (`ID`)
);
  

CREATE TABLE IF NOT EXISTS `POPULATION` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `TOTAL` INT NULL,
    `BELOW_POVERTY` INT NULL,
    `AGE_BAND_FK` INT NULL REFERENCES `AGE_BAND` (`ID`),
    `RACE_FK` INT  NULL REFERENCES `RACE` (`ID`),
    `YEAR_FK` INT NULL REFERENCES `YEAR` (`ID`),
    `MARITAL_STATUS_FK` INT NULL REFERENCES `MARITAL_STATUS` (`ID`),
    `RESIDENCE_FK` INT NULL REFERENCES `RESIDENCE` (`ID`),
    `DISABILITY_STATUS_FK` INT NULL REFERENCES `DISABILITY_STATUS` (`ID`),
    `FAMILY_STATUS_FK` INT NULL REFERENCES `FAMILY_STATUS` (`ID`),
    `NATIVITY_FK` INT NULL REFERENCES `NATIVITY` (`ID`),
    `REGION_FK` INT NULL REFERENCES `REGION` (`ID`),
    PRIMARY KEY (`ID`),
    INDEX `AGE_BAND_FK_IDX` (`AGE_BAND_FK` ASC),
    CONSTRAINT `AGE_BAND_FK` FOREIGN KEY (`AGE_BAND_FK`) REFERENCES `AGE_BAND` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    INDEX `RACE_FK_IDX` (`RACE_FK` ASC),
    CONSTRAINT `RACE_FK` FOREIGN KEY (`RACE_FK`) REFERENCES `RACE` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    INDEX `YEAR_FK_idx` (`YEAR_FK` ASC),
    CONSTRAINT `YEAR_FK` FOREIGN KEY (`YEAR_FK`) REFERENCES `YEAR` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    INDEX `MARITAL_STATUS_FK_IDX` (`MARITAL_STATUS_FK` ASC),
    CONSTRAINT `MARITAL_STATUS_FK` FOREIGN KEY (`MARITAL_STATUS_FK`) REFERENCES `MARITAL_STATUS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    INDEX `RESIDENCE_FK_idx` (`RESIDENCE_FK` ASC),
    CONSTRAINT `RESIDENCE_FK` FOREIGN KEY (`RESIDENCE_FK`) REFERENCES `RESIDENCE` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    INDEX `DISABILITY_STATUS_FK_IDX` (`DISABILITY_STATUS_FK` ASC),
    CONSTRAINT `DISABILITY_STATUS_FK` FOREIGN KEY (`DISABILITY_STATUS_FK`) REFERENCES `DISABILITY_STATUS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    INDEX `FAMILY_STATUS_FK_IDX` (`FAMILY_STATUS_FK` ASC),
    CONSTRAINT `FAMILY_STATUS_FK` FOREIGN KEY (`FAMILY_STATUS_FK`) REFERENCES `FAMILY_STATUS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    INDEX `NATIVITY_FK_IDX` (`NATIVITY_FK` ASC),
    CONSTRAINT `NATIVITY_FK` FOREIGN KEY (`NATIVITY_FK`) REFERENCES `NATIVITY` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    INDEX `REGION_FK_IDX` (`REGION_FK` ASC),
    CONSTRAINT `REGION_FK` FOREIGN KEY (`REGION_FK`) REFERENCES `REGION` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

  
